### ISSUE TITLE
Error in Webpack example

### ISSUE THREAD

**Issue by amitaibu** [halfzebra/elm-aframe#11]
```
ERROR in ./src/elm/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
-- TYPE MISMATCH ------------------------------------------ ././src/elm/Geom.elm

The argument to function `repeat` is causing a mismatch.

66|               repeat 10000
                         ^^^^^
Function `repeat` is expecting the argument to be:

    String

But it is:

    number

Detected errors in 1 module.

    at ChildProcess.<anonymous> (/Library/WebServer/Documents/elm-learn/elm-aframe/examples/webpack/node_modules/node-elm-compiler/index.js:141:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 @ ./src/static/index.js 2:10-34
```

**Comment by amitaibu** [comment]
(PR will follow)
